[package]
name = "mdlabelgen"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
imageproc = "0.25.0"
ab_glyph = "0.2.29"
dirs = "5.0.1"
toml = "0.8.19"
serde = "1.0.210"
serde_derive = "1.0.210"
shellexpand = "3.1.0"
