[[labels]]
artist = "YOB"
title = "Clearing the Path to Ascend"
release_year = "2014"
cover = "/home/mattvh/Downloads/clearingthepath.jpg"

[[labels]]
artist = "killie"
title = "Retrial of the Criminal Begins"
release_year = "2018"
cover = "/home/mattvh/Downloads/killie.jpg"
